<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Stef Heyenrath</Authors>
    <TargetFrameworks>net48;net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <DefineConstants>$(DefineConstants);NOEF</DefineConstants>
    <RootNamespace>LinqKitCoreTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LinqKit.Core\LinqKit.Core.csproj" />
  </ItemGroup>

</Project>
