name: Main workflow

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    
    env:
      Prerelease: ci
      CONFIGURATION: ReleaseForGithubActions

    steps:
    - name: Print GITHUB_RUN_NUMBER
      run: |
        echo "GITHUB_RUN_NUMBER is ${env:GITHUB_RUN_NUMBER}"
          
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: | 
          8.0.x
          10.0.x
     
    - name: Build Projects
      run: |
        dotnet build ./src/LinqKit.Core/LinqKit.Core.csproj -c $env:CONFIGURATION
        dotnet build ./src/LinqKit/LinqKit.csproj -c $env:CONFIGURATION
        dotnet build ./src/LinqKit.EntityFramework/LinqKit.EntityFramework.csproj -c $env:CONFIGURATION
        dotnet build ./src/LinqKit.Microsoft.EntityFrameworkCore8/LinqKit.Microsoft.EntityFrameworkCore8.csproj -c $env:CONFIGURATION
        dotnet build ./src/LinqKit.Microsoft.EntityFrameworkCore9/LinqKit.Microsoft.EntityFrameworkCore9.csproj -c $env:CONFIGURATION
        dotnet build ./src/LinqKit.Microsoft.EntityFrameworkCore10/LinqKit.Microsoft.EntityFrameworkCore10.csproj -c $env:CONFIGURATION
        dotnet build ./src/LinqKit.Z.EntityFramework.Classic/LinqKit.Z.EntityFramework.Classic.csproj -c $env:CONFIGURATION
    
    - name: Run Tests
      run: |
        dotnet test ./tests/LinqKit.Core.Tests/LinqKit.Core.Tests.csproj -c $env:CONFIGURATION
        dotnet test ./tests/LinqKit.Tests/LinqKit.Tests.csproj -c $env:CONFIGURATION
        dotnet test ./tests/LinqKit.EntityFramework.Tests/LinqKit.EntityFramework.Tests.csproj -c $env:CONFIGURATION
        dotnet test ./tests/LinqKit.Microsoft.EntityFrameworkCore8.Tests -c $env:CONFIGURATION
        dotnet test ./tests/LinqKit.Microsoft.EntityFrameworkCore9.Tests -c $env:CONFIGURATION
        dotnet test ./tests/LinqKit.Microsoft.EntityFrameworkCore10.Tests -c $env:CONFIGURATION
